#!/usr/bin/env bash

# tput_colors - Demonstrate color combinations.

printHeaderA () {
  tput sgr0
  #echo "                                Background Colors"
  for n in {0..7}; do
    #set_background=$(tput setab $bg_color)
    #echo -n $set_background$set_foreground
    printf ' BgColor%1s  ' $n
  done
  echo $(tput sgr0)
  #echo ""
}

printHeaderB () {
  tput sgr0
  #echo "                                Background Colors"
  for n in {8..15}; do
    #set_background=$(tput setab $bg_color)
    #echo -n $set_background$set_foreground
    printf ' BgColor%2s ' $n
  done
  echo $(tput sgr0)
  #echo ""
}

printSetBgA () {
  for fg_color in 0 8 1 9 2 10 3 11 4 12 5 13 6 14 7 15; do
    set_foreground=$(tput setaf $fg_color)
    for bg_color in {0..7}; do
      set_background=$(tput setab $bg_color)
      echo -n $set_background$set_foreground
      printf ' F:%2s B:%2s ' $fg_color $bg_color
    done

    tput sgr0
    printf '   FgColor%2s' $fg_color
    echo $(tput sgr0)
  done
}

printSetBgB () {
  for fg_color in 0 8 1 9 2 10 3 11 4 12 5 13 6 14 7 15; do
    set_foreground=$(tput setaf $fg_color)
    for bg_color in {8..15}; do
      set_background=$(tput setab $bg_color)
      echo -n $set_background$set_foreground
      printf ' F:%2s B:%2s ' $fg_color $bg_color
    done

    tput sgr0
    printf '   FgColor%2s' $fg_color
    echo $(tput sgr0)
  done
}

echo "                             Print .Xresources Colors"
echo ""
printHeaderA
echo ""
printSetBgA
echo ""
printHeaderB
echo ""
printSetBgB
echo ""
