#!/usr/bin/env bash

#nix-shell -p python39Packages.gtts sox

#pico2wave -w /tmp/test.wav "$1" && aplay /tmp/test.wav

#gtts-cli -l id  "bunga itu warna merah dan bau wangi" | play -t mp3 -

#nix-shell -p python39Packages.gtts sox --run 'gtts-cli -l id "Percubaan 1 2 3" | play -t mp3 -'
nix-shell -p python39Packages.gtts sox --run "gtts-cli -l id \"${1}\" | play -t mp3 --volume 0.5 - "
