#!/usr/bin/env bash

function printTheVars {
  echo "XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}"
  echo "TMUX_TMPDIR: ${TMUX_TMPDIR}"
}

function exportTheVars {
  export TMUX_TMPDIR="${XDG_RUNTIME_DIR}"
}

#printTheVars
exportTheVars
#printTheVars

# Check/test the tmux
#tmux ls

# Run the tmux
tmux a -t main
